name: Binary release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: android
            goarch: arm64
            cgo: 1
            api: 21
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'

      - name: Setup Android NDK
        if: matrix.goos == 'android'
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: false

      - name: Build
        run: make -C cli cli \
          GOOS=${{ matrix.goos }} \
          GOARCH=${{ matrix.goarch }} \
          CGO_ENABLED=${{ matrix.cgo }} \
          ANDROID_API=${{ matrix.api }} \
          ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }} \
          VERSION=${{ github.ref_name }}

      - name: Upload to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} cli/dist/*
